package org.jpokemon.api;

import static org.junit.Assert.assertTrue;

import java.util.Random;

import org.jpokemon.api.trainers.PokemonTrainer;
import org.jpokemon.api.trainers.TrainerIDGenerator;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;

/**
 * Tests the generation of unique trainer IDs.
 * 
 * @author atheriel@gmail.com
 */
@RunWith(JUnit4.class)
public class IDGeneratorTest {

	/**
	 * Checks if the trainer ID is correctly generated by using a constant seed.
	 */
	@Test
	public void testIDGeneration() {
		TrainerIDGenerator generator = new TrainerIDGenerator(new Random(1337));
 		PokemonTrainer trainerBob = new PokemonTrainer().setName("Bob");
		try {
			trainerBob.setID(generator.generateUniqueID());
		} catch (Exception e) {
			e.printStackTrace();
		}
		assertTrue("Trainer Bob has the correct Trainer ID.", trainerBob.getID() == 6741);
	}
}
